GET http://localhost:8080/hello
Accept: application/json


###

POST http://localhost:8080/yzh
Content-Type: application/x-www-form-urlencoded

name=杨梓皓

###
 GET http://localhost:8080/ebook/list?name=Mysql